### ISSUE TITLE
Save for oldest version possible

### ISSUE THREAD

**Issue by 3esmit** [JKISoftware/HAL-Webinar#1]
There is one particular reason for saving in LabVIEW 2015? I understand that sometimes some features are unavaliable on older versions. 
I'm currently downloading an avaliation version of LV2015 to test this code, maybe I pull request this project in older version.

**Comment by francois-normandin** [comment]
I believe I used some of the latest Utility Variant VIs in 2015. 
If you want to backsave the project, it is likely that some of the VIs will need to be modified to use either OpenG Variant tools or some of the deprecated Utility Variant functions from vi.lib.

Thanks for your interest in this webinar! Let me know if I can be of any help.

**Comment by 3esmit** [comment]
This VIs are sadly password protected so I could not check if they had the same output but seems like so, as the terminals are the same and the VI names are get type. 

![image](https://cloud.githubusercontent.com/assets/224810/16852004/796a2b38-49dc-11e6-8691-be442f06bc8c.png)
![image](https://cloud.githubusercontent.com/assets/224810/16852014/8672ccc2-49dc-11e6-88f0-ab5734b49dc9.png)

I created the pull request, everything seems to work in my 2013 version. I believe this Webinar is very important for LabVIEW ecosystem and should be ported to the older version possible.

**Comment by francois-normandin** [comment]
Thanks Ricardo. I'll checkout your backsaved code when I get a minute!
State Machine Objects have been created with 2013, so this is as far back as we will maintain the base class code. I'll take note to prepare any future webinars in LV2013. ;-)

Indeed, the Utility Variant VIs are password-protected. They are likely wrapping a direct call to LabVIEW.exe.

**Comment by 3esmit** [comment]
Its just missing the fix in Camera.TestLauncher that is a Error Clean.vi not replaced for 2013 version. Also I don't find those JKI user interface libraries

**Comment by francois-normandin** [comment]
JKI User Interface libraries should have been removed. It is an invalid cross-linking somewhere. Possibly in a disabled diagram. They should not be called anymore.

**Comment by 3esmit** [comment]
They are used in Camera.TestLauncher. I will remove them from repository then.

**Comment by 3esmit** [comment]
Done.

**Comment by francois-normandin** [comment]
Merged.
